[package]
name = "instagrambot"
version = "0.1.2"
authors = ["NotAefka <notaefka@protonmail.com>"]
edition = "2018"

[dependencies]
json = "0.11.15"
webdriver = { git = "https://github.com/Mubelotix/webdriver", rev = "23f7d2f" }
env_logger = "0.6.2"