[package]
name = "instagrambot"
version = "0.1.0"
authors = ["NotAefka <notaefka@protonmail.com>"]
edition = "2018"

[dependencies]
json = "0.11.15"
webdriver = { git = "https://github.com/Mubelotix/webdriver" }
env_logger = "0.6.2"